### ISSUE TITLE
Door sensor initialization and setup.

### ISSUE THREAD

**Issue by mkejmart** [Nickman5030/Boise-Brewing-Dev#12]
#11 

**Abstract**
Create code to integrate with sensor to count/register entry into Boise Brewing. Create a simple GUI allowing customization of deals, Create physical interface to turn pi on/off and tracking on/off. Have a Hardware Spec sheet of all components required.

**Acceptance Criteria**

- [x] Hardware is connected to Pi in a repeatable and stable way.

- [x] Sensor detects people passing it

- [ ] Sensor output is interpreted as an increment to customers counted

- [ ] Digital interface can adjust prize awards and intervals

- [ ] Physical button/switch to shut off prize awarding

**Comment by Nickman5030** [comment]
Collin Comments: 
- easy interface to adjust counting
- prefers a physical interface
- GUI interface shows stats of customers
- Photograph winning/special customers
