### ISSUE TITLE
Compile Wish List of Needed Hardware

### ISSUE THREAD

**Issue by Nickman5030** [Nickman5030/Boise-Brewing-Dev#18]
#12
Research and compile all the hardware needed for this sprint. Comment things needed

**Comment by rexplin** [comment]
https://www.amazon.com/LoveRPi-Raspberry-Starter-Raspbian-Desktop/dp/B01IYBZEV6/ref=sr_1_15?crid=2WWNQYJNCR5U2&keywords=raspberry%2Bpi%2B3&qid=1568411551&sprefix=rasp%2Caps%2C207&sr=8-15&th=1

raspberry pi, power supply, usb, sd card with os. $50 each, need 2-4

**Comment by Neelik** [comment]
[Infrared Motion Sensors - 5 pack for $10](https://www.amazon.com/DIYmall-HC-SR501-Motion-Infrared-Arduino/dp/B012ZZ4LPM/ref=sr_1_3?keywords=raspberry+pi+infrared+sensor&qid=1568577288&sr=8-3#customerReviews)
[Ultrasonic Sensors - 5 pack for $10 with some connectors](https://www.amazon.com/Smraza-Ultrasonic-Distance-Mounting-Duemilanove/dp/B01JG09DCK/ref=sr_1_4?crid=3R73W2UPW0WCZ&keywords=raspberry+pi+ultrasonic+sensor&qid=1568578036&sprefix=raspberry+pi+ultr%2Caps%2C189&sr=8-4)

**Comment by Nickman5030** [comment]
https://www.amazon.com/Waterproof-600leds-Flexible-Changing-Controller/dp/B01IQOV13G/ref=sr_1_7?crid=3VEVRISKGZ3IL&keywords=led+strip+lights&qid=1568514730&s=home-garden&sprefix=LED+%2Caps%2C227&sr=1-7
30ft of LED cable with power adapter, IR remote/receiver, and adhesive backing

https://www.amazon.com/VIPMOON-Connector-Silicon-Fastener-Flexible/dp/B01ESYJAV8/ref=sr_1_7?keywords=led+strip+brackets&qid=1568594588&s=home-garden&sr=1-7
Screw-in LED brackets

https://www.amazon.com/Mounting-KINDPMA-Adhesive-Brackets-Waterproof/dp/B07DWCR8WV/ref=sr_1_5?keywords=led+strip+brackets&qid=1568594647&s=home-garden&sr=1-5
Adhesive LED brackets

3D print covers for Ultrasonic sensors
https://www.ebay.com/i/202473691076?chn=ps&norover=1&mkevt=1&mkrid=711-117182-37290-0&mkcid=2&itemid=202473691076&targetid=593772056093&device=c&mktype=pla&googleloc=9029602&poi=&campaignid=2086169716&mkgroupid=76147899766&rlsatarget=aud-412677883135:pla-593772056093&abcId=1141016&merchantid=6296724&gclid=CjwKCAjwwvfrBRBIEiwA2nFiPUI3DAx-Q9aUiwB7d_-xCCNlrEM6V_uBDSE6p9KmXo4abQYfC7bVsRoCDtQQAvD_BwE
or 
Use PVC pipe fittings cut to size
https://www.amazon.com/s?k=black+pvc+pipe&ref=nb_sb_noss_1

3D Print enclosure for Raspberry Pi
(can be done at the library for sensor covers as well.)
