### ISSUE TITLE
Utilize Either a Ultrasonic Sensor or a PIR sensor

### ISSUE THREAD

**Issue by Nickman5030** [Nickman5030/Boise-Brewing-Dev#20]
#12
A Ultrasonic sensor or PIR sensor must be mounted to the door to track customers entering. Decide on which will be used

**Comment by rexplin** [comment]
Article comparing PIR and ultrasonic: https://www.facilitiesnet.com/lighting/article/Occupancy-Sensors-Passive-Infrared-Ultrasonic-and-Dual-Technology--9608

**Comment by rexplin** [comment]
Will Likely use both together to prevent false positives. Next sprint will need testing to see what configuration it needs.
